### ISSUE TITLE
{flint} exists on CRAN

### ISSUE THREAD

**Issue by adamhsparks** [jaganmn/flint#2]
When I saw that someone had starred this repo, I thought it was this one, already on CRAN, <https://github.com/etiennebacher/flint/>.

I wasn’t sure if you were aware.

**Comment by jaganmn** [comment]
That package does not appear to be available on CRAN or on Bioconductor.

```r
> getOption("repos")
                                                    CRAN 
                           "https://cloud.r-project.org" 
                                                BioCsoft 
           "https://bioconductor.org/packages/3.20/bioc" 
                                                 BioCann 
"https://bioconductor.org/packages/3.20/data/annotation" 
                                                 BioCexp 
"https://bioconductor.org/packages/3.20/data/experiment" 
> db <- available.packages()
> any(db[, "Package"] == "flint")
[1] FALSE
```

Having said that, I'm aware of it.  Indeed, I'll have to change the name of this package if that one finds its way to CRAN or Bioconductor first.  My submission to CRAN must wait until the next Rtools release, probably in spring.

**Comment by adamhsparks** [comment]
Whoops. You're right! _Mea culpa_.

**Comment by adamhsparks** [comment]
quick get it there first! 🥇
